### ISSUE TITLE
Many internal server errors

### ISSUE THREAD

**Issue by Ambrevar** [PromyLOPh/guix-install-action#14]
We use guix-install-action at https://github.com/atlas-engineer/nyxt/ (thanks a lot by the way, very useful!) but recently it has been failing increasingly at this line:

https://github.com/PromyLOPh/guix-install-action/blob/v1/action.yml#L33

See for instance
https://github.com/atlas-engineer/nyxt/runs/6399684430?check_suite_focus=true 👍 

```log
Run PromyLOPh/guix-install-action@v1
Run echo LANG=en_US.utf8 >> $GITHUB_ENV
Run wget -nv https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -O guix-install.sh
2022-05-12 04:09:03 URL:https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh [20087/20087] -> "guix-install.sh" [1]
https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz:
2022-05-12 04:09:03 ERROR 500: Internal Server Error.
Error: Process completed with exit code 8.
```

Looks like the Guix CI is erroring out.  Any idea?

**Comment by aadcg** [comment]
This is a wild guess but it seems that something changed in the latest tarball job.

Compare [the latest one](https://ci.guix.gnu.org/build/767430/details) with the [one before](https://ci.guix.gnu.org/build/715209/details), and notice the missing "Build outputs" link.

**Comment by aadcg** [comment]
It seems I'm right, see [my fork succeding](https://github.com/aadcg/guix-install-action/actions/runs/2312201756).

It's an ugly solution, but it seems the only thing we could do temporarily is to hardcore the link that points to the latest available tarball.

**Comment by Ambrevar** [comment]
What's the magic number 584 for?

**Comment by aadcg** [comment]
It's a magic number indeed. But, as explained above, there's no better solution at the moment.

**Comment by Ambrevar** [comment]
Does this number change over time?

**Comment by aadcg** [comment]
Now I see your concern. No, it doesn't, so we're good.

**Comment by PromyLOPh** [comment]
It should be working again. It would be nice to fallback to a non-CI URL in case it breaks again. But I believe release 1.3.0 does not support the `yes` pipe mechanism.

**Comment by aadcg** [comment]
It does, but I don't understand why the query now works. Care to explain? :)

**Comment by PromyLOPh** [comment]
Guix’ CI is just unreliable and breaks constantly.
