### ISSUE TITLE
Guix install action stuck after guix install script change

### ISSUE THREAD

**Issue by jonasfreimuth** [PromyLOPh/guix-install-action#16]
Currently, the install action terminates (on Ubuntu20.04 runners) after creating the systemd entry ([example log](https://github.com/PromyLOPh/guix-install-action/files/9746636/failed_pigx_sars-cov-2_build_run_44_attempt_2.log)), i.e. at the first yes/no prompt.

This is the first point that the guix-install script as it is executed by the action encounters the recently modified `prompt_yes_no()` function. It was modified in [this commit](https://git.savannah.gnu.org/cgit/guix.git/commit/etc/guix-install.sh?id=6a2e303d3a49baf7c222a70b91f453e9efd456c6). Apparently, the changes lead to the `yes` utility no longer adequatly stopping the prompt...

**Comment by PromyLOPh** [comment]
I reported it [here](https://lists.gnu.org/archive/html/guix-devel/2022-10/msg00099.html). I’m guessing that `_flush` is a bad idea for non-interactive uses, but we’ll see what Maxim says.

**Comment by jonasfreimuth** [comment]
Ah ok thank you. 👍 I also just submitted a bug report, but that may not be through the moderation pipeline yet...

**Comment by jonasfreimuth** [comment]
In case relevant: [Guix bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=58417)

**Comment by jonasfreimuth** [comment]
Closing, as this was fixed at the actual source of the issue ([here](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=e46bb5fd5af3adb931e0930326c60a7c2e4cbe4e)).
