### ISSUE TITLE
ci.guix.gnu.org returns 502 bad gateway when retriving guix-binary

### ISSUE THREAD

**Issue by ROCKTAKEY** [PromyLOPh/guix-install-action#19]
Thanks for your maintenance.

The URL https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz , which is written in [here](https://github.com/PromyLOPh/guix-install-action/blob/82df1aaaee302fe9926c15f94dd89e8f68301980/action.yml#L37), responses "502 bad gateway". I tried it yesterday and today but the responses are same.

**Comment by PromyLOPh** [comment]
I’m not maintaining the Guix CI and have no way of fixing it. We have to wait for the Guix sysadmins.

**Comment by ROCKTAKEY** [comment]
Thanks.
I reported it because I don't know it is temporal degradation of Guix CI or breaking changes.

If it is just temporary degradation,  I am sorry to waste your time.  Then please close this issue.

**Comment by alam0rt** [comment]
Seems like the build is "still succeeding"

https://ci.guix.gnu.org/build/383069/details

**Comment by ymfsing** [comment]
Today, this error disappeared in my usage.

**Comment by ROCKTAKEY** [comment]
Works fine, too. Thanks.

**Comment by ymfsing** [comment]
Today, I have encountered the same error once again. It is possible that there are certain limitations to the guix ci. However, we can try using this URL instead: https://ftpmirror.gnu.org/gnu/guix/guix-binary-1.4.0.x86_64-linux.tar.xz .

**Comment by ROCKTAKEY** [comment]
I've also encountered several times even after closing this.
I agree to download the guix binary from ftp.gnu.org or ftpmirror.gnu.org. What do you think @PromyLOPh?

**Comment by PromyLOPh** [comment]
Works again, it seems. But I agree we need a fallback, even though installing from the last release is not optimal (very long `guix pull`).
