### ISSUE TITLE
URL that fetches Guix binary is down

### ISSUE THREAD

**Issue by aadcg** [PromyLOPh/guix-install-action#22]
The [URL that fetches the Guix binary](https://github.com/PromyLOPh/guix-install-action/blob/v1/action.yml#L36) is not working.

See an example of a CI action failing below.

https://github.com/atlas-engineer/nyxt/actions/runs/4927423723/jobs/8804386083

Is there a workaround? Thanks.

**Comment by PromyLOPh** [comment]
See #19. There is no workaround right now, unfortunately.

**Comment by aadcg** [comment]
As I've expected. Thanks for the answer @PromyLOPh.

I believe I read somewhere that the Guix servers will undergo maintenance but I can't remember where.

**Comment by aadcg** [comment]
[I've asked in the mailing list whether there's an alternative](https://lists.gnu.org/archive/html/guix-devel/2023-06/msg00161.html).

**Comment by aadcg** [comment]
I received a reply. [It should be fixed when this issue is closed](https://issues.guix.gnu.org/64317).

**Comment by camoy** [comment]
This still seems to be a problem. URL is currently returning 500 error code.

```
Run wget -nv https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz -O guix-binary-nightly.x86_64-linux.tar.xz
https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz:
2023-09-16 05:09:31 ERROR 500: Internal Server Error.
```

**Comment by sigprof** [comment]
Yes, that thing fails again, although in a slightly different way:
```
Run wget -nv https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz -O guix-binary-nightly.x86_64-linux.tar.xz
https://ci.guix.gnu.org/download/1153:
2023-11-04 17:00:20 ERROR 500: Internal Server Error.
```
Apparently `ci.guix.gnu.org` replies with `{"error":"Could not find the requested build product."}`, even though the second-to-last build tarball seems to be available.

Annoyingly, fetching the latest release tarball from `ftpmirror.gnu.org` is not reliable too (apparently they have some unreliable mirrors in their rotation):
```
Run wget -nv https://ftpmirror.gnu.org/gnu/guix/guix-binary-1.4.0.x86_64-linux.tar.xz -O guix-binary-nightly.x86_64-linux.tar.xz
https://mirrors.tripadvisor.com/gnu/guix/guix-binary-1.4.0.x86_64-linux.tar.xz:
2023-11-04 17:34:20 ERROR 500: Internal Server Error.
```

**Comment by aadcg** [comment]
Thanks for sharing this piece of information @sigprof. While it is still an issue, it seems related to Guix and not to this project.

**Comment by ghisvail** [comment]
Should this issue be escalated again to the mailing list?

**Comment by PromyLOPh** [comment]
Yes please, there’s nothing we can do here.

**Comment by ghisvail** [comment]
It looks like the Guix website now provides a [download URL](https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz) to  the their latest successful CI build.

I don't understand why this URL cannot be used / is not working here.

**Comment by PromyLOPh** [comment]
How is that URL different from the one we’re using?
