### ISSUE TITLE
Guix died unexpectedly 

### ISSUE THREAD

**Issue by bvbfan** [PromyLOPh/guix-install-action#23]
```
building /gnu/store/f13b12c633n0xdjasawm9rihamr7yv9d-gcc-cross-x86_64-linux-gnu-10.3.0.drv...
building /gnu/store/b7nqdcpqikxi1q3j0v6fm91805c4zmdk-x86_64-linux-gnu-toolchain-10.3.0.drv...
substitute: 
substitute: updating substitutes from 'https://ci.guix.gnu.org/'...   0.0%guix substitute: error: TLS error in procedure 'write_to_session_record_port': Error in the push function.
guix environment: error: `/gnu/store/4lmpqf8dnk86avq5xa2l6bznxnmrz27x-guix-1.4.0-7.44bbfc2/bin/guix substitute' died unexpectedly
```
It's happen every time on Github action and not happen on real machine or VM Ubuntu 22.04

**Comment by PromyLOPh** [comment]
Not something we can fix here, see for example this Guix issue: https://issues.guix.gnu.org/47867

**Comment by ghost** [comment]
has there been a solution since then? unfortunately i still get this error. :(

**Comment by bvbfan** [comment]
> has there been a solution since then? unfortunately i still get this error. :(

It happens on every run in github actions, a temporary solution could be to have only one outstanding action (even then it fails very often)

**Comment by esgn** [comment]
Any solution or workaround for this issue ? Thanks in advance
