### ISSUE TITLE
The default value for `channels` refers to a nonexistent Guix mirror

### ISSUE THREAD

**Issue by sigprof** [PromyLOPh/guix-install-action#24]
The https://github.com/guix-mirror/guix.git mirror stopped updating some time ago, and apparently was just removed completely instead of fixing.  The default value for the `channels` input refers to that mirror; that reference should be removed to make the action work without specifying that input manually.

**Comment by PromyLOPh** [comment]
Should be fixed with release 1.5. Thanks!
