### ISSUE TITLE
Showcase docker image output in docs

### ISSUE THREAD

**Issue by OverkillGuy** [PromyLOPh/guix-install-action#4]
Hello, just started using your Github Action, and I've super easily been able to use it to create docker image tarballs. 
I feel this is so nice as to be worth advertising on the cover page of the project, as well as in the demo yaml.

See [my half-baked docker image building PR on a toy Rust project](https://github.com/OverkillGuy/qrxfil/pull/31/files), though my understanding of Github Actions is limited, you may do something nicer than I did.

Yes, this just means showing that `--format docker` is supported in the READMEs. And yes it's `guix` doing all the hard work, but it's kind of a massive positive for a CI system, showcasing creating docker images.

Feel free to close this armchair contribution if it's not worth it. Cheers

**Comment by PromyLOPh** [comment]
Hey, I think this is a good idea and I tried to improve the description/example in 6571378325bba021155e5c998c35c02a3dd7969e (see branch “docker”). Is that enough visibility?

Do you know whether the Docker image generated in https://github.com/PromyLOPh/guix-install-action/actions/runs/803899670 actually work out-of-the-box? I can’t test that unfortunately.

**Comment by OverkillGuy** [comment]
Change in docs looks good!

I tested the docker image (downloaded the hello_docker zip, had to unzip it to get the targz that `docker load -i` expects, meh) and it successfully shows a "hello, World!" on stdout. 

So, yeah, great! Thanks for the quick turnaround.

**Comment by PromyLOPh** [comment]
Merged and tagged as v1.2. Thank you for the suggestion and testing!
